### ISSUE TITLE
SyntaxError: Unexpected token t in JSON at position 112

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#80]
This happens after I pulled upstream.

![image](https://user-images.githubusercontent.com/16500161/50510414-8273b680-0ac4-11e9-84dd-09a622337b5b.png)

Seems the fault happens when rendering markdown file. My blog is publically available at fr0der1c/blog, I guess this can help you find the problem.

There is some problem with rendering after applying upstream commits these days. Another problem is that the line separater seems broken, and the paragraphs after a quote turn into part of a quote.

![image](https://user-images.githubusercontent.com/16500161/50510630-6cb2c100-0ac5-11e9-9838-b11a234a745c.png)

**Comment by ciokan** [comment]
This points to a malformed code snippet. Can you please give me the code that you tried to encode here (I need the clean bit because this is the malformed extraction):

`{"code":"curl -XPUT \"http://localhost:9200/_snapshot/my_backup\" \n-H 'Content-Type: application/json' \n-d'{ࠜ"type\": \"fs\",ࠜ"settings\": {ࠠ \"location\": \"/var/backups\"࠽}' \n-u elastic:password","language":"shell"}`

I'll look into the the other issues meanwhile.

**Comment by ciokan** [comment]
The blockquote issue should be fixed with: https://github.com/QardsJs/qards/commit/6b944d82a243de0b1e6593e80d320034cd6f502e

**Comment by fr0der1c** [comment]
Yes. The blockquote issue fixed now.

I'm not sure why the code has been malformed. I use rich text editor only. The original code is:
```
curl -XPUT "http://localhost:9200/_snapshot/my_backup" -H 'Content-Type: application/json' -d'
{
  "type": "fs",
  "settings": {
    "location": "/var/backups"
  }
}' -u elastic:password
```

**Comment by ciokan** [comment]
Closing this. Please reopen if the bug appears again
